<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SngTool\**" />
    <EmbeddedResource Remove="SngTool\**" />
    <None Remove="SngTool\**" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="SngTool\SngCli\SngCli.csproj">
      <PrivateAssets>All</PrivateAssets>
	  <ExcludeAssets>Compile</ExcludeAssets>
	</ProjectReference>
  </ItemGroup>

</Project>
